# **Concatenación de arreglos**


La concatenación, o unión de dos arreglos en NumPy, se realiza principalmente a través de la función `concatenate`:

In [8]:
import numpy as np

In [9]:
#Concatenación de listas
x = [1, 2, 3]
y = [4, 5, 6]

x + y

[1, 2, 3, 4, 5, 6]

In [10]:
#Concatenación en numpy

xa = np.array(x)
ya = np.array(y)

xa + ya

array([5, 7, 9])

In [11]:
np.concatenate([xa, ya])

array([1, 2, 3, 4, 5, 6])

Podemos concatenar más de dos arreglos al tiempo:

In [12]:
za = np.array([7, 8, 9])

np.concatenate([xa, ya, za])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

`concatenate` también se puede usar para arreglos bidimensionales. Recuerde que las filas corresponden al eje 1 (axis = 1) y las columnas al eje 0 (axis = 0)


<p><img alt="Colaboratory logo" height="300px" src="https://i.imgur.com/KYPgvhf.png" align="left" hspace="10px" vspace="0px"></p>

In [ ]:
df.apply(funcion_suma, args = (...), axis = 1)

In [13]:
a = np.arange(8,14).reshape(3,2)
a

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [14]:
np.concatenate((a, a), axis = 0)

array([[ 8,  9],
       [10, 11],
       [12, 13],
       [ 8,  9],
       [10, 11],
       [12, 13]])

Si queremos realizar la concatenación a lo largo del eje 1, debemos especificar el eje por medio de un argumento por palabra clave:

In [15]:
np.concatenate((a, a), axis = 1)

array([[ 8,  9,  8,  9],
       [10, 11, 10, 11],
       [12, 13, 12, 13]])

In [16]:
np.concatenate((a, a))

array([[ 8,  9],
       [10, 11],
       [12, 13],
       [ 8,  9],
       [10, 11],
       [12, 13]])

La función `vstack()` es equivalente a la concatenación a lo largo del primer eje (axis=0). Al igual que `concatenate()`, recibe como argumento una secuencia de arreglos que, en este caso, deben tener la misma forma a lo largo de todos los ejes, excepto el primero. Los arreglos unidimensionales deben tener la misma longitud:

In [17]:
# dimensiones mixtas
a = np.array( [1, 2, 3])
b = np.array([[4, 5, 6],
              [7, 8, 9]])

np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
try:
  np.hstack((a, b))
except:
  print("No son rectangulares")

No son rectangulares


Similarmente, la función `hstack()` realiza una concatenación a lo largo del segundo eje (axis=1), y los arreglos que toma como argumento deben coincidir en la forma a lo largo de este eje. Los arreglos unidimensionales pueden ser de cualquier longitud

In [22]:
#dimensiones mixtas

a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 11).reshape(2, 2)

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]]


In [23]:
np.hstack((a, b))

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

### **Slicing o segmentación en Python**

```
l[inicio: final(no incluyente): paso]
```

In [27]:
l = [i for i in range(0, 160, 10)]
l

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]

In [28]:
l[5]

50

In [29]:
l[6]

60

In [30]:
l[7 : 11]

[70, 80, 90, 100]

In [31]:
l[0 : 5]

[0, 10, 20, 30, 40]

In [32]:
l[ : 5]

[0, 10, 20, 30, 40]

In [33]:
l[5 : 16]

[50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]

In [34]:
l[5 : ]

[50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]

In [39]:
l[5 : : -1]

[50, 40, 30, 20, 10, 0]

In [36]:
l[3 : 7 : 2]

[30, 50]

<p><a name="ind"></a></p>

# **Indexación y segmentación**

Los arreglos de NumPy tienen la misma semántica de indexación y segmentación que las listas de Python cuando se trata de acceder a elementos o subarreglos.




In [41]:
a = np.arange(8)

print(f"a: {a}")
print(f"a[2]: {a[2]}") #Indexación
print(f"a[2:5]: {a[2:5]}") #Segmentación

a: [0 1 2 3 4 5 6 7]
a[2]: 2
a[2:5]: [2 3 4]


Debido a que los arreglos de NumPy son n-dimensionales, podemos segmentar a lo largo de todos y cada uno de los ejes. Consideremos la siguiente lista de listas en Python

In [42]:
# definiendo una lista de listas de forma (3,3)
L = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Por ejemplo, si queremos crear una lista de Python que contenga todas las filas y las primeras dos columnas de la lista L podríamos escribir

In [43]:
[sub_l[:2] for sub_l in L]

[[1, 2], [4, 5], [7, 8]]

El número de ciclos `for` anidados que se necesita para segmentar listas de listas es igual al número de dimensiones menos uno (en este caso $2-1=1$).

En NumPy, en lugar de indexar por un segmento, podemos indexar por una tupla de segmentos, cada uno de los cuales actúa en sus propias dimensiones. Definamos el arreglo `L` con NumPy y realicemos la segmentación anterior:


In [44]:
arr = np.array(L)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr[0:3, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

Los ciclos `for` para la segmentación multidimensional son manejados implícitamente por NumPy. Esto hace que realizar segmentaciones complejas sea mucho más rápido que escribir los ciclos `for` explícitamente en Python. Veamos algunos ejemplos:

In [48]:
#creamos un arreglo de dimensiones 4x4
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
#seleccionar la primer fila (equivalente a a[0,:])
#a[0]
a[0,:]

array([0, 1, 2, 3])

In [51]:
# seleccionar la primera columna
a[:,0]

array([ 0,  4,  8, 12])

In [52]:
#segmentar las filas pares y las columnas impares.
a[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [53]:
#segmentar la matriz interna de 2x2.
a[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [56]:
#invertir las primeras 3 filas, tomando las primeras 3 columnas
a[2::-1, :3]

array([[ 8,  9, 10],
       [ 4,  5,  6],
       [ 0,  1,  2]])

**Ejercicio 1**: Escriba un programa para crear un nuevo arreglo que sea el promedio de cada triplete consecutivo de elementos del siguiente arreglo

<p><img alt="Colaboratory logo" height="70px" src="https://i.imgur.com/XoHovZd.png" align="left" hspace="10px" vspace="0px"></p>

In [61]:
L = [1,2,3,2,4,6,1,2,12,0,-12,6]
arr = np.array([1,2,3,2,4,6,1,2,12,0,-12,6]).reshape(4,-1)
new_arr = np.mean(arr, axis=1)
new_arr

array([ 2.,  4.,  5., -2.])

In [63]:
0 / 3

0.0

In [71]:
d = dict()
s = 0
for count, i in enumerate(L):
  s += i
  if (count - 2) % 3 == 0:
    var = (count - 2)/ 3
    d[var] = s / 3
    s = 0
d.values()

dict_values([2.0, 4.0, 5.0, -2.0])

<p><a name="enm"></a></p>

## **Enmascaramiento**

El enmascaramiento aparece cuando deseamos extraer, modificar, o manipular valores en un arreglo de acuerdo con algún criterio.

Ya vimos cómo utilizar ufuncs para operaciones aritméticas básicas y otro tipo de operaciones más complejas. NumPy implementa también operadores de comparación como ufuncs:

In [72]:
x = np.arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
x < 6

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

El resultado es un arreglo booleano. Dado un arreglo booleano, hay una serie de operaciones útiles que podemos implementar.

Podemos utilizar la función `np.sum` junto con los operadores de comparación para realizar conteos dentro del arreglo:

In [74]:
# numero de elementos menores a 6
np.sum(x < 6)

5

Con `np.sum` podemos realizar este tipo de conteos a lo largo de las filas o columnas, utilizando el argumento por palabra clave `axis`:

In [75]:
# numero de elementos menores a 6 por columna
np.sum(x < 6, axis = 0)

array([2, 2, 1])

In [76]:
# numero de elementos menores a 6 por fila
np.sum(x < 6, axis = 1)

array([3, 2, 0])

Podemos también tener múltiples condiciones en un conteo, utilizando los operadores lógicos `&` (and) y `|` (or)

In [78]:
# verdadero si ambos verdaderos
print((x > 1) & (x < 6))
np.sum((x > 1) & (x < 6))

[[False  True  True]
 [ True  True False]
 [False False False]]


4

In [79]:
# verdadero en caso en que alguno de los dos sea verdadero
print((x < 2) | (x > 6))
np.sum((x < 2) | (x > 6))

[[ True False False]
 [False False False]
 [ True  True  True]]


4

Una herramienta muy poderosa es usar los arreglos booleanos como máscaras, para seleccionar subconjuntos particulares de los datos mismos.

Volviendo a nuestra arreglo `x` anterior, supongamos que queremos un arreglo de todos los valores en `x` que sean menores que, digamos, 5. Para seleccionar estos valores del arreglo, simplemente podemos indexar con este arreglo booleano; esto se conoce como una operación de enmascaramiento:

In [80]:
x[x > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [81]:
x > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Lo que se devuelve es un arreglo unidimensional con todos los valores que cumplen la condición; en otras palabras, todos los valores en las posiciones en las que el arreglo de máscara es `True`.

**Ejercicio 2:** Escriba una función que, dado un número entero `n`, retorne:

* Un arreglo con los primeros números pares hasta `n`, incluyendo.
* Un arreglo con los primeros números múltiplos de tres hasta `n`, incluyendo.

<p><a name="sof"></a></p>

# **Indexación sofisticada**

Anteriormente vimos cómo acceder y modificar porciones de arreglos usando índices simples (por ejemplo, `arr[0]`), segmentos (por ejemplo, `arr[: 5]`) y máscaras booleanas (por ejemplo, `arr[arr> 0]`). Veremos ahora otro estilo de indexación de arreglos, conocido como *indexación sofisticada*, la cual nos permite acceder y modificar muy rápidamente subconjuntos complicados de los valores de un arreglo.

La indexación sofisticada es conceptualmente simple: significa pasar una lista de índices en lugar de un entero, para acceder a múltiples elementos del arreglo a la vez. Veamos un ejemplo:

In [82]:
a = np.arange(10, 21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [83]:
np.array([a[0], a[2], a[7]])

array([10, 12, 17])

In [86]:
a[[0,2,7]]

array([10, 12, 17])

In [84]:
indi = [0, 2, 7]
a[indi]

array([10, 12, 17])

Con el indexado sofisticado, la forma del resultado refleja la forma del arreglo de índices más que la forma del arreglo que se está indexando:

In [87]:
a = np.arange(0, 91, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [89]:
ind = np.array([[3, 7],
                [5, 8]])

a[ind]

array([[30, 70],
       [50, 80]])

El indexado sofisticado funciona también en múltiples dimensiones. Veámoslo en el siguiente ejemplo:

In [90]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Como en la indexación estándar, el primer índice hace referencia a las filas y el segundo a las columnas:

In [91]:
filas = [0, 1, 2]
columnas = [2, 1, 3]

In [92]:
a[filas, columnas]

array([ 2,  5, 11])

In [95]:
np.where((a == 2) | (a == 5) | (a == 11))

(array([0, 1, 2]), array([2, 1, 3]))

Los valores el en arreglo corresponden a `a[0,2]`, `a[1,1]` y `a[2,3]` respectivamente.